### ISSUE TITLE
Undefined variable: "$co-gray-flat1"

### ISSUE THREAD

**Issue by eyeseast** [frontlinepbs/fl-base-blueprint#26]
Here's the stacktrace:

```
Error: Undefined variable: "$co-gray-flat1".
        on line 53 of /Users/dan_nolan/Dropbox/work/Projects/**frontline active/blueprint/fl-base-blueprint/_scss/_typography.scss, in `blockquote'
        from line 59 of /Users/dan_nolan/Dropbox/work/Projects/**frontline active/blueprint/fl-base-blueprint/_scss/_typography.scss
        from line 6 of /Users/dan_nolan/Dropbox/work/Projects/**frontline active/blueprint/fl-base-blueprint/_scss/base.scss

Backtrace:
/Users/dan_nolan/Dropbox/work/Projects/**frontline active/blueprint/fl-base-blueprint/_scss/_typography.scss:53:in `blockquote'
/Users/dan_nolan/Dropbox/work/Projects/**frontline active/blueprint/fl-base-blueprint/_scss/_typography.scss:59
/Users/dan_nolan/Dropbox/work/Projects/**frontline active/blueprint/fl-base-blueprint/_scss/base.scss:6
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/script/tree/variable.rb:49:in `_perform'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/script/tree/node.rb:50:in `perform'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/script/tree/list_literal.rb:63:in `block in _perform'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/script/tree/list_literal.rb:63:in `map'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/script/tree/list_literal.rb:63:in `_perform'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/script/tree/node.rb:50:in `perform'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:395:in `visit_prop'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:36:in `visit'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/stack.rb:79:in `block in with_base'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/stack.rb:115:in `with_frame'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/stack.rb:79:in `with_base'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:158:in `visit'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:364:in `block (4 levels) in visit_mixin'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:364:in `map'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:364:in `block (3 levels) in visit_mixin'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:364:in `block (2 levels) in visit_mixin'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:84:in `perform_arguments'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:359:in `block in visit_mixin'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/stack.rb:98:in `block in with_mixin'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/stack.rb:115:in `with_frame'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/stack.rb:98:in `with_mixin'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:347:in `visit_mixin'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:36:in `visit'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/stack.rb:79:in `block in with_base'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/stack.rb:115:in `with_frame'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/stack.rb:79:in `with_base'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:158:in `visit'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:431:in `block (2 levels) in visit_rule'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:431:in `map'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:431:in `block in visit_rule'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:429:in `visit_rule'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:36:in `visit'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/stack.rb:79:in `block in with_base'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/stack.rb:115:in `with_frame'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/stack.rb:79:in `with_base'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:158:in `visit'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:326:in `block (2 levels) in visit_import'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:326:in `map'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:326:in `block in visit_import'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/stack.rb:88:in `block in with_import'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/stack.rb:115:in `with_frame'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/stack.rb:88:in `with_import'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:323:in `visit_import'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:36:in `visit'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/stack.rb:79:in `block in with_base'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/stack.rb:115:in `with_frame'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/stack.rb:79:in `with_base'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:158:in `visit'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:52:in `map'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:52:in `visit_children'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:36:in `block in visit'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:36:in `visit'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:157:in `visit'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:8:in `visit'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/root_node.rb:36:in `css_tree'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/tree/root_node.rb:20:in `render'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/engine.rb:278:in `render'
/usr/local/lib/ruby/gems/2.1.0/gems/compass-import-once-1.0.5/lib/compass/import-once/engine.rb:17:in `block in render'
/usr/local/lib/ruby/gems/2.1.0/gems/compass-import-once-1.0.5/lib/compass/import-once/engine.rb:29:in `with_import_scope'
/usr/local/lib/ruby/gems/2.1.0/gems/compass-import-once-1.0.5/lib/compass/import-once/engine.rb:16:in `render'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/plugin/compiler.rb:492:in `update_stylesheet'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/plugin/compiler.rb:215:in `block in update_stylesheets'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/plugin/compiler.rb:209:in `each'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/plugin/compiler.rb:209:in `update_stylesheets'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/plugin/compiler.rb:471:in `on_file_changed'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/lib/sass/plugin/compiler.rb:328:in `block in watch'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/vendor/listen/lib/listen/listener.rb:252:in `call'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/vendor/listen/lib/listen/listener.rb:252:in `on_change'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/vendor/listen/lib/listen/listener.rb:290:in `block in initialize_adapter'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/vendor/listen/lib/listen/adapter.rb:254:in `call'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/vendor/listen/lib/listen/adapter.rb:254:in `report_changes'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/vendor/listen/lib/listen/adapter.rb:323:in `poll_changed_directories'
/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.21/vendor/listen/lib/listen/adapter.rb:299:in `block in start_poller'
```

**Comment by eyeseast** [comment]
This may be part of #22
